# This file was generated by GoReleaser. DO NOT EDIT.
cask "gitai" do
  name "gitai"
  desc "AI-powered Git Assistant"
  homepage "https://github.com/artback/gitai"
  version "0.8.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gitai"

  on_macos do
    on_intel do
      url "https://github.com/artback/gitai/releases/download/v#{version}/gitai_#{version}_darwin_x86_64.tar.gz",
        verified: "github.com/artback/gitai"
      sha256 "2c021030974722935c99e87431890a68124078f12b4a47ddece149f24024e04b"
    end
    on_arm do
      url "https://github.com/artback/gitai/releases/download/v#{version}/gitai_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/artback/gitai"
      sha256 "5aa3fe51f8fac34a59171b0463fd13824b8189450cc10dab8c0e0bd615c4defd"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/artback/gitai/releases/download/v#{version}/gitai_#{version}_linux_x86_64.tar.gz",
        verified: "github.com/artback/gitai"
      sha256 "dd28fe72fa3441d0b7445e2d27da689a030a0911d5ef9b9bb413a133b07fbe16"
    end
    on_arm do
      url "https://github.com/artback/gitai/releases/download/v#{version}/gitai_#{version}_linux_arm64.tar.gz",
        verified: "github.com/artback/gitai"
      sha256 "208412232e4a9a015cb7238dd356c29c2bf6cba2204e0abad72e91298b7a96ee"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gitai"]
    end
  end

  # No zap stanza required
end
