# This file was generated by GoReleaser. DO NOT EDIT.
cask "gitai" do
  name "gitai"
  desc "AI-powered Git Assistant"
  homepage "https://github.com/artback/gitai"
  version "0.2.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gitai"

  on_macos do
    on_intel do
      url "https://github.com/artback/gitai/releases/download/v#{version}/gitai_#{version}_darwin_x86_64.tar.gz",
        verified: "github.com/artback/gitai"
      sha256 "6da3cd052fca1fac9a548e5d7762f313d4145d1af01188d9fb97fc9f7d58e7c2"
    end
    on_arm do
      url "https://github.com/artback/gitai/releases/download/v#{version}/gitai_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/artback/gitai"
      sha256 "24ae7d6e91c57b3acb5789ab03a26c45dadc71a4c1e78af453638adf95263518"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/artback/gitai/releases/download/v#{version}/gitai_#{version}_linux_x86_64.tar.gz",
        verified: "github.com/artback/gitai"
      sha256 "cfc3f4966d9d513173b8878eb4a916ad1af48062288c6f407aea1a97f4794015"
    end
    on_arm do
      url "https://github.com/artback/gitai/releases/download/v#{version}/gitai_#{version}_linux_arm64.tar.gz",
        verified: "github.com/artback/gitai"
      sha256 "4209bef59cc15a727d946d4918b778a0c29bc696b7c5a46a98da194360f1aacb"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gitai"]
    end
  end

  # No zap stanza required
end
