# This file was generated by GoReleaser. DO NOT EDIT.
cask "gitai" do
  name "gitai"
  desc "AI-powered Git Assistant"
  homepage "https://github.com/artback/gitai"
  version "0.3.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gitai"

  on_macos do
    on_intel do
      url "https://github.com/artback/gitai/releases/download/v#{version}/gitai_#{version}_darwin_x86_64.tar.gz",
        verified: "github.com/artback/gitai"
      sha256 "240974aa98ee01c48d7d547222e0cab2bef6b1aef2e414355a90324c63b7c7be"
    end
    on_arm do
      url "https://github.com/artback/gitai/releases/download/v#{version}/gitai_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/artback/gitai"
      sha256 "c9e394da62ac8413e41dfbf6f10525cd500050f8347d1431e125c82e9b2a6877"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/artback/gitai/releases/download/v#{version}/gitai_#{version}_linux_x86_64.tar.gz",
        verified: "github.com/artback/gitai"
      sha256 "2baf2f733be7187e1c48719e86db58052b232d5dc31054b5659f6bcbafe2f5ff"
    end
    on_arm do
      url "https://github.com/artback/gitai/releases/download/v#{version}/gitai_#{version}_linux_arm64.tar.gz",
        verified: "github.com/artback/gitai"
      sha256 "e38e195030ec219c89354a791a9fe05799f4bd50f247fc920f8fac6d456086e4"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gitai"]
    end
  end

  # No zap stanza required
end
